"""add index

Revision ID: 9e0538afd7af
Revises: c2542a1d79f6
Create Date: 2022-12-12 17:52:41.606037

"""
from alembic import op, context
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e0538afd7af'
down_revision = 'c2542a1d79f6'
branch_labels = None
depends_on = None


def upgrade():
    schema_upgrades()
    data_upgrades()

def downgrade():
    data_downgrades()
    schema_downgrades()

def schema_upgrades():
    """schema upgrade migrations go here"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dogs', 'height',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.create_index(op.f('ix_dogs_name'), 'dogs', ['name'], unique=False)
    # ### end Alembic commands ###

def schema_downgrades():
    """schema downgrade migrations go here"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dogs_name'), table_name='dogs')
    op.alter_column('dogs', 'height',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###

def data_upgrades():
    """optional data upgrade migrations go here"""
    pass

def data_downgrades():
    """optional data downgrade migrations go here"""
    pass
