"""add toys v2

Revision ID: 7060d7125032
Revises: eae063ee79c3
Create Date: 2022-12-12 18:33:48.563101

"""
from alembic import op, context
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7060d7125032'
down_revision = 'eae063ee79c3'
branch_labels = None
depends_on = None


def upgrade():
    schema_upgrades()
    data_upgrades()

def downgrade():
    data_downgrades()
    schema_downgrades()

def schema_upgrades():
    """schema upgrade migrations go here"""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def schema_downgrades():
    """schema downgrade migrations go here"""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def data_upgrades():
    """optional data upgrade migrations go here"""
    pass

def data_downgrades():
    """optional data downgrade migrations go here"""
    pass
