"""add toys

Revision ID: eae063ee79c3
Revises: 9e0538afd7af
Create Date: 2022-12-12 18:29:40.715216

"""
from alembic import op, context
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eae063ee79c3'
down_revision = '9e0538afd7af'
branch_labels = None
depends_on = None


def upgrade():
    schema_upgrades()
    data_upgrades()

def downgrade():
    data_downgrades()
    schema_downgrades()

def schema_upgrades():
    """schema upgrade migrations go here"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('toys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dog_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def schema_downgrades():
    """schema downgrade migrations go here"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('toys')
    # ### end Alembic commands ###

def data_upgrades():
    """optional data upgrade migrations go here"""
    pass

def data_downgrades():
    """optional data downgrade migrations go here"""
    pass
